---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonmain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonmain
  template:
    metadata:
      labels:
        app: pythonmain
    spec:
      containers:
        - name: pythonmain
          image: temp1ar/pythonmain:latest
          ports:
            - name: web
              containerPort: 8080
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 250m
          readinessProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 30
            failureThreshold: 2
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: web
            failureThreshold: 2
            periodSeconds: 10
          volumeMounts:
            - name: config
              subPath: message
              mountPath: /etc/message.txt
      volumes:
        - name: config
          configMap:
            name: config
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - general
      # tolerations:
      # - key: team
      #   operator: Equal
      #   value: devops
      #   effect: NoSchedule
