---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
spec:
  selector:
    app: pythonmain
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
